name: Deploy design system site 
# site:  designsystems.webstandards.ca.gov
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Build Site
        run: |
          npm install
          npm run site:build
      - name: Write robots.txt
        run: |
          echo 'User-agent: *' > _site/robots.txt
          echo 'Allow: /' >> _site/robots.txt
          echo 'Sitemap: https://designsystem.webstandards.ca.gov/sitemap.xml' >> docs/robots.txt
      - name: Run site accessibility tests
        run: |
          npm run test:setup
          npm run test:site
      # Push built site files to S3 production bucket    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'designsystem.webstandards.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./_site # only move built directory

      # Invalidate Cloudfront production distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'E1GP67RJOCAKQE'
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    